# Generated by Django 3.2.16 on 2022-12-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_data_migration"),
    ]

    operations = []
